package com.librarymanagement.controller;
import com.librarymanagement.dto.ApiDtos.ProfileInput;import com.librarymanagement.dto.ApiDtos.Register;import com.librarymanagement.entity.*;import com.librarymanagement.repository.UserRepository;import com.librarymanagement.service.LibraryService;import jakarta.validation.Valid;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/members") public class MemberController{
 private final UserRepository users;private final LibraryService service;public MemberController(UserRepository u,LibraryService s){users=u;service=s;}
 @GetMapping @PreAuthorize("hasRole('LIBRARIAN')") public List<Map<String,Object>> all(@RequestParam(required=false)String search){return users.findByRole(Role.MEMBER).stream().filter(u->search==null||u.getName().toLowerCase().contains(search.toLowerCase())||u.getEmail().contains(search.toLowerCase())).map(service::publicUser).toList();}
 @PostMapping @PreAuthorize("hasRole('LIBRARIAN')") public Map<String,Object> create(@Valid @RequestBody Register in){return service.publicUser(service.register(in));}
 @GetMapping("/{id}") @PreAuthorize("hasRole('LIBRARIAN')") public Map<String,Object> get(@PathVariable Long id){User u=users.findById(id).orElseThrow(()->new NoSuchElementException("Member not found."));if(u.getRole()!=Role.MEMBER)throw new NoSuchElementException("Member not found.");return service.publicUser(u);}
 @PutMapping("/{id}") @PreAuthorize("hasRole('LIBRARIAN')") public Map<String,Object> update(@PathVariable Long id,@Valid @RequestBody ProfileInput in){User u=users.findById(id).orElseThrow(()->new NoSuchElementException("Member not found."));u.setName(in.name());u.setEmail(in.email());u.setPhone(in.phone());return service.publicUser(users.save(u));}
 @PatchMapping("/{id}/status") @PreAuthorize("hasRole('LIBRARIAN')") public Map<String,Object> status(@PathVariable Long id,@RequestParam AccountStatus status){User u=users.findById(id).orElseThrow(()->new NoSuchElementException("Member not found."));u.setAccountStatus(status);return service.publicUser(users.save(u));}
 @GetMapping("/me") public Map<String,Object> me(Authentication a){return service.publicUser(service.user(a.getName()));}
 @PutMapping("/me") public Map<String,Object> updateMe(Authentication a,@Valid @RequestBody ProfileInput in){User u=service.user(a.getName());u.setName(in.name());u.setEmail(in.email());u.setPhone(in.phone());return service.publicUser(users.save(u));}
}
