package com.librarymanagement.controller;
import com.librarymanagement.entity.*;import com.librarymanagement.repository.*;import com.librarymanagement.service.LibraryService;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/notifications") public class NotificationController{
 private final LibraryNotificationRepository notes;private final NotificationPreferenceRepository prefs;private final UserRepository users;private final LibraryService service;
 public NotificationController(LibraryNotificationRepository n,NotificationPreferenceRepository p,UserRepository u,LibraryService s){notes=n;prefs=p;users=u;service=s;}
 @GetMapping public Map<String,Object> list(Authentication a){User u=service.user(a.getName());return Map.of("items",notes.findByRecipientIdOrderByCreatedAtDesc(u.getId()).stream().map(service::notificationView).toList(),"unreadCount",notes.countByRecipientIdAndIsReadFalse(u.getId()));}
 @PutMapping("/{id}/read") public Map<String,Object> read(@PathVariable Long id,Authentication a){var n=notes.findByIdAndRecipientId(id,service.user(a.getName()).getId()).orElseThrow(()->new NoSuchElementException("Notification not found."));n.setRead(true);return service.notificationView(notes.save(n));}
 @PutMapping("/read-all") public Map<String,Object> readAll(Authentication a){User u=service.user(a.getName());notes.findByRecipientIdOrderByCreatedAtDesc(u.getId()).forEach(n->n.setRead(true));notes.flush();return Map.of("success",true);}
 @PostMapping @PreAuthorize("hasRole('LIBRARIAN')") public Map<String,Object> announce(@RequestBody Map<String,String> in){String title=Objects.requireNonNullElse(in.get("title"),"Library announcement");String message=Objects.requireNonNullElse(in.get("message"),"");users.findByRole(Role.MEMBER).forEach(u->service.createNotification(u,title,message,"ANNOUNCEMENT"));return Map.of("success",true,"recipients",users.findByRole(Role.MEMBER).size());}
 @GetMapping("/preferences") public Map<String,Object> preferences(Authentication a){User u=service.user(a.getName());return prefView(prefs.findByMemberId(u.getId()).orElseGet(()->{NotificationPreference p=new NotificationPreference();p.setMember(u);return prefs.save(p);}));}
 @PutMapping("/preferences") public Map<String,Object> updatePreferences(Authentication a,@RequestBody NotificationPreference input){User u=service.user(a.getName());NotificationPreference p=prefs.findByMemberId(u.getId()).orElseGet(NotificationPreference::new);p.setMember(u);p.setDueDateAlerts(input.isDueDateAlerts());p.setOverdueAlerts(input.isOverdueAlerts());p.setNewBookAlerts(input.isNewBookAlerts());p.setAnnouncementAlerts(input.isAnnouncementAlerts());return prefView(prefs.save(p));}
 private Map<String,Object> prefView(NotificationPreference p){return Map.of("dueDateAlerts",p.isDueDateAlerts(),"overdueAlerts",p.isOverdueAlerts(),"newBookAlerts",p.isNewBookAlerts(),"announcementAlerts",p.isAnnouncementAlerts());}
}
