package com.librarymanagement.controller;
import com.librarymanagement.entity.*;import com.librarymanagement.repository.*;import com.librarymanagement.service.LibraryService;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;import java.time.LocalDate;import java.util.*;
@RestController @RequestMapping("/api/reports") @PreAuthorize("hasRole('LIBRARIAN')") public class ReportController{
 private final LibraryService service;private final BookRepository books;private final LoanRepository loans;public ReportController(LibraryService s,BookRepository b,LoanRepository l){service=s;books=b;loans=l;}
 @GetMapping("/dashboard") public Map<String,Object> dashboard(){return service.dashboard();}
 @GetMapping("/borrowing-trends") public List<Map<String,Object>> borrowingTrends(){return monthly(false);}
 @GetMapping("/return-trends") public List<Map<String,Object>> returnTrends(){return monthly(true);}
 private List<Map<String,Object>> monthly(boolean returns){int year=LocalDate.now().getYear();long[] counts=new long[12];for(Loan l:loans.findAll()){LocalDate date=returns?l.getReturnDate():l.getBorrowDate();if(date!=null&&date.getYear()==year)counts[date.getMonthValue()-1]++;}String[] names={"Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"};List<Map<String,Object>> out=new ArrayList<>();for(int i=0;i<12;i++)out.add(Map.of("month",names[i],"count",counts[i]));return out;}
 @GetMapping("/most-borrowed") public List<Map<String,Object>> mostBorrowed(){Map<Long,Long> count=new HashMap<>();loans.findAll().forEach(l->count.merge(l.getBook().getId(),1L,Long::sum));return count.entrySet().stream().sorted(Map.Entry.<Long,Long>comparingByValue().reversed()).limit(10).map(e->{var b=service.book(e.getKey());return Map.<String,Object>of("book",b.getTitle(),"author",b.getAuthor(),"borrowCount",e.getValue());}).toList();}
 @GetMapping("/genre-distribution") public List<Map<String,Object>> genreDistribution(){Map<String,Long> count=new TreeMap<>();books.findAll().forEach(b->count.merge(b.getGenre()==null?"Uncategorized":b.getGenre(),1L,Long::sum));return count.entrySet().stream().map(e->Map.<String,Object>of("genre",e.getKey(),"count",e.getValue())).toList();}
 @GetMapping("/inventory") public List<Map<String,Object>> inventory(){return books.findAll().stream().map(service::bookView).toList();}
 @GetMapping("/overdue") public List<Map<String,Object>> overdue(){return loans.overdue(LocalDate.now()).stream().map(service::loanView).toList();}
 @GetMapping(value="/transactions.csv",produces="text/csv") public String csv(){StringBuilder out=new StringBuilder("id,book,member,borrow_date,due_date,return_date,status\n");for(Loan l:loans.findAllByOrderByBorrowDateDesc()){out.append(l.getId()).append(',').append(quote(l.getBook().getTitle())).append(',').append(quote(l.getMember().getName())).append(',').append(l.getBorrowDate()).append(',').append(l.getDueDate()).append(',').append(l.getReturnDate()==null?"":l.getReturnDate()).append(',').append(l.isOverdue()?"OVERDUE":l.getStatus()).append('\n');}return out.toString();}
 private String quote(String s){return "\""+s.replace("\"","\"\"")+"\"";}
}
