package com.librarymanagement.config;

import com.librarymanagement.entity.*;import com.librarymanagement.repository.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.boot.CommandLineRunner;import org.springframework.context.annotation.Bean;import org.springframework.context.annotation.Configuration;import org.springframework.security.crypto.password.PasswordEncoder;
import java.time.LocalDate;import java.util.List;

@Configuration public class DemoData {
 @Bean CommandLineRunner seed(UserRepository users,BookRepository books,LoanRepository loans,LibraryNotificationRepository notifications,NotificationPreferenceRepository preferences,PasswordEncoder encoder,@Value("${DEMO_LIBRARIAN_EMAIL:admin@library.com}")String adminEmail,@Value("${DEMO_LIBRARIAN_PASSWORD:}")String adminPassword,@Value("${DEMO_MEMBER_PASSWORD:}")String memberPassword){return args->{
  if(books.count()==0){String[][] data={
   {"Clean Code","Robert C. Martin","9780132350884","Software Engineering","Prentice Hall","2008"},{"Design Patterns","Erich Gamma et al.","9780201633610","Software Engineering","Addison-Wesley","1994"},{"The Pragmatic Programmer","Andrew Hunt","9780135957059","Software Engineering","Addison-Wesley","2019"},{"Introduction to Algorithms","Thomas H. Cormen","9780262046305","Computer Science","MIT Press","2022"},{"The Linux Programming Interface","Michael Kerrisk","9781593272203","Operating Systems","No Starch Press","2010"},{"Computer Networking","James Kurose","9780136681557","Computer Science","Pearson","2021"},{"Database System Concepts","Abraham Silberschatz","9781260084504","Databases","McGraw-Hill","2019"},{"The Art of Cybersecurity","Peter Schawacker","9781119613065","Cybersecurity","Wiley","2020"},{"Algorithms to Live By","Brian Christian","9781627790369","Science","Henry Holt","2016"},{"The Code Book","Simon Singh","9780385495325","Cybersecurity","Anchor","1999"},{"Atomic Habits","James Clear","9780735211292","Personal Development","Avery","2018"},{"Sapiens","Yuval Noah Harari","9780062316097","History","Harper","2015"},{"The Midnight Library","Matt Haig","9780525559474","Literature","Viking","2020"},{"Educated","Tara Westover","9780399590504","Memoir","Random House","2018"},{"Dune","Frank Herbert","9780441172719","Science Fiction","Ace","1965"},{"The Alchemist","Paulo Coelho","9780062315007","Literature","HarperOne","2014"},{"The Selfish Gene","Richard Dawkins","9780198788607","Science","Oxford University Press","2016"},{"Thinking, Fast and Slow","Daniel Kahneman","9780374533557","Psychology","Farrar, Straus and Giroux","2011"},{"A Brief History of Time","Stephen Hawking","9780553380163","Science","Bantam","1998"},{"The Design of Everyday Things","Don Norman","9780465050659","Design","Basic Books","2013"}};
   for(int i=0;i<data.length;i++){Book b=new Book();b.setTitle(data[i][0]);b.setAuthor(data[i][1]);b.setIsbn(data[i][2]);b.setGenre(data[i][3]);b.setPublisher(data[i][4]);b.setPublicationYear(Integer.parseInt(data[i][5]));b.initializeQuantity(2+i%4);b.setDescription("A recommended title from the Northstar Library collection.");books.save(b);}}
  if(!adminPassword.isBlank()&&!users.existsByEmail(adminEmail)){User a=new User();a.setName("Library Administrator");a.setEmail(adminEmail);a.setPasswordHash(encoder.encode(adminPassword));a.setRole(Role.LIBRARIAN);users.save(a);}
  if(!memberPassword.isBlank()&&users.findByRole(Role.MEMBER).isEmpty()){String[] names={"Aarav Sharma","Priya Nair","Ishita Das","Rohan Mehta","Ananya Iyer","Kabir Kapoor","Maya Rao","Arjun Sen"};for(int i=0;i<names.length;i++){User m=new User();m.setName(names[i]);m.setEmail(i==0?"student@library.com":"member"+(i+1)+"@library.com");m.setPasswordHash(encoder.encode(memberPassword));m.setPhone("+91 98"+String.format("%08d",i+10000000));m=users.save(m);NotificationPreference pref=new NotificationPreference();pref.setMember(m);preferences.save(pref);if(i<4&&books.count()>i){Book b=books.findAll().get(i);if(b.getAvailableCopies()>0){b.decrementAvailable();Loan l=new Loan();l.setMember(m);l.setBook(b);l.setBorrowDate(LocalDate.now().minusDays(i==0?3:20));l.setDueDate(l.getBorrowDate().plusDays(14));if(i==1){l.setStatus(LoanStatus.RETURNED);l.setReturnDate(l.getBorrowDate().plusDays(8));b.incrementAvailable();}loans.save(l);}}LibraryNotification n=new LibraryNotification();n.setRecipient(m);n.setTitle("Welcome to Northstar Library");n.setMessage("Your library account is ready. Search the catalog to find your next read.");n.setType("ANNOUNCEMENT");notifications.save(n);}}
 };}
}
